apiVersion: scripts.scropt.io/v1
kind: MoonScript
metadata:
  name: example
spec:
  code: |
    class Thing
      name: "unknown"

    class Person extends Thing
      say_name: => print "Hello, I am #{@name}!"

    with Person!
      .name = "MoonScript"
      \say_name!
