# This rule is not used by the project scropt itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to scripts.scropt.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: scropt
    app.kubernetes.io/managed-by: kustomize
  name: luascript-viewer-role
rules:
- apiGroups:
  - scripts.scropt.io
  resources:
  - luascripts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scripts.scropt.io
  resources:
  - luascripts/status
  verbs:
  - get
