# This rule is not used by the project scropt itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over scripts.scropt.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: scropt
    app.kubernetes.io/managed-by: kustomize
  name: moonscript-admin-role
rules:
- apiGroups:
  - scripts.scropt.io
  resources:
  - moonscripts
  verbs:
  - '*'
- apiGroups:
  - scripts.scropt.io
  resources:
  - moonscripts/status
  verbs:
  - get
