---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scripts.scropt.io
  resources:
  - luascripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scripts.scropt.io
  resources:
  - luascripts/finalizers
  verbs:
  - update
- apiGroups:
  - scripts.scropt.io
  resources:
  - luascripts/status
  verbs:
  - get
  - patch
  - update
