apiVersion: scripts.scropt.io/v1
kind: LuaScript
metadata:
  name: example
spec:
  code: |
    log("Hello, I am Lua!")
    for _, p in pairs({ctx, discovery, client, core}) do
      if p["__NAME__"] ~= nil then
          print(p["__NAME__"])
      elseif p["__TYPE__"] ~= nil then
          print(p["__TYPE__"])
      else
        print("")
      end
      print("-------------------------------------------")
      for k, v in pairs(p) do 
        print(k, v)
      end
      print("")
    end
    apiResources = discovery.ServerPreferredResources()
    for key, apiResourceList in pairs(apiResources) do 
      print("API Group:\n", apiResourceList.__PTR__)
    end
    --[[
    local podList = core.PodList:new()
    for k, v in pairs(podList:get()) do
        print(k, v)
    end
    local listOptions = client.ListOptions:new()
    client.List(ctx, podList, listOptions)
    local result = podList:get()
    for _, v in ipairs(result.Items) do
      print(v)
      print("")
    end
    --]]
